name: '💡 Feature request'
description: Would you like to see a new capability in a Kinde library? Let us know here.
title: 'Feature request: (fill in)'
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to request a new feature 👍🏼. Be sure to check the [public roadmap](https://updates.kinde.com/board), as we could be about to start work on it, or it's pegged for the future.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To save time and prevent duplicating work, please complete the following.
      options:
        - label: I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
          required: true
        - label: I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
          required: true
        - label: I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: What is the problem you’re trying to solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What solution would you like to see?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Is there anything else that’s important for the core team to know?
